routes/web.php
<?php

Route::get('/', function () {
    return view('front-page.home2');
})->name('pendaftaran.pondokit');

Route::get('form-register','FrontPage\FrontPageController@formRegister')->name('form-register');
Route::get('form-search','FrontPage\FrontPageController@formSearch')->name('form-search');

Route::resource('psb','FrontPage\FrontPageController');
Route::post('psb/search','FrontPage\FrontPageController@search')->name('psb.search');

Auth::routes();

app/Http/Controllers/FrontPage/FrontPageController.php
<?php

namespace App\Http\Controllers\FrontPage;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Models\Internship;
use Illuminate\Support\Facades\Auth; //untukmenggunakan Controller Auth
use Illuminate\Support\Facades\DB;
use Yajra\DataTables\DataTables;
use App\Events\Register\RegisterEvent;
use Illuminate\Support\Facades\Mail;

class FrontPageController extends Controller
{
    public function index()
    {
        //
    }
    public function formRegister(){
        return view('front-page.register.register');
    }

    public function formSearch(){
        return view('front-page.trafic.trafic-search');
    }

    public function store(Request $request)
    {
        $reg = new Internship;
        $target = [
            // Personal Data
            'photo' => 'required|image ',
            'name' => 'required|min:5|max:150',
            'birth_date' => 'required|max:150',       
            'address' => 'required',
            'province' => 'required',
            'department' => 'required',
            'sex' => 'required',
            // Contact
            'wa' => 'required|unique:internships|numeric',
            'fb' => 'required|max:150',
            'email' => 'required|unique:internships|email|max:150',
            // Education
            'dep_school' => 'required|max:150',
            'school' => 'required|max:150',
            'phone_teacher' => 'required|numeric',
            // Family
            'phone_parent' => 'required|numeric',
            'father_name' => 'required|max:150',
            'mother_name' => 'required|max:150',
            // Kuesioner
            'ust_idol' => 'required|max:150',
            'smoke' => 'required',
            'religion' => 'required|max:150',
            'pondok_know' => 'required',
            'it_skill' => 'required',
            'like_lesson' => 'required',
            'pay' => 'required',
            'start' => 'required',
            'finish' => 'required'
            
        ];
        $msg = [
            // Personal Data
            'photo.required' => 'Foto diri  Wajib di isi',
            'photo.mimes' => 'Format Foto harus JPG / JPEG / GIF / PNG',
            'photo.image' => 'Foto harus bertipe format JPEG / PNG / JPG / GIF',
            'name.required' => 'Wajib Mengisi Nama',
            'name.max' => 'Nama Maximal 150 karakter',
            'birth_date.required' => 'Tanggal Lahir Wajib di Isi',
            'address.required' => 'Alamat wajib di isi',
            'province.required' => 'Provinsi wajib di isi',
            'sex.required' => 'Jenis Kelamin Wajib di isi',
            'department.required' => 'Jurusan Wajib di isi',

            // Contact
            'wa.required' => 'Nomor WhatsApp Wajib di isi',
            'wa.unique' => 'Nomor WhatsApp sudah terdaftar',
            'wa.numeric' => 'Nomor WhatsApp harus bertipe angka',
            'email.required' => 'Email Wajib di isi',
            'email.unique' => 'Email sudah terdaftar gunakan email lain',
            'email.email' => 'Harus di isi Alamat Email',
            'email.max' => 'Email Maximal 150 karakter',
            'fb.required' => 'Link Facebook Wajib di isi',

            // Education
            'dep_school.required' => 'Jurusan Sekolah Wajib di isi',
            'dep_school.max' => 'Jurusan Sekolah Maximal 150 karakter',
            'school.required' => 'Sekolah Asal Wajib di isi',
            'school.max' => 'Sekolah Maximal 150 karakter',
            'phone_teacher.required' => 'Nomor HandPhone Wali Murid / Guru Wajib di isi',

            // Family
            'phone_parent.required' => 'Nomor Telepon Orang Tua Wajib di isi',
            'phone_parent.numeric' => 'Nomor Telepon Orang Tua harus bertipe angka',
            'father_name.required' => 'Nama Ayah Wajib di isi',
            'father_name.max' => 'Nama Ayah Maximal 150 karakter',
            'mother_name.required' => 'Nama Ibu Wajib di isi',
            'mother_name.max' => 'Nama Ibu Maximal 150 karakter',

            // Kuesioner
            'ust_idol.required' => 'Ustadz Idola Wajib di isi',
            'ust_idol.max' => 'Ustadz Idola Maximal 150 karakter',
            'smoke.required' => 'Perokok atau Bukan  Wajib di isi',
            'religion.required' => 'Pemahaman Agama Wajib di isi',
            'religion.max' => 'Pemahaman Agama Maximal 150 karakter',
            'pondok_know' => 'Wajib di isi',
            'it_skill.required' => 'Skill IT yang dimiliki Wajib di isi',
            'like_lesson.required' => 'Pelajaran yang di suka Wajib di isi',
            'pay.required' => 'Wajib di isi',
            'start.required' => 'Wajib di isi',
            'finish.required' => 'Wajib di isi'
        ];

        $request->validate($target, $msg);
            // Personal Data
            $reg->name = $request->name;
            $reg->sex = $request->sex;
            $reg->birth_date = date('Y-m-d', strtotime($request->birth_date));
            $reg->province = $request->province;
            $reg->department = $request->department;
            $reg->address = $request->address;
            // Contact
            $reg->wa = $request->wa;
            $reg->email = $request->email;
            $reg->fb = $request->fb;
            // Education
            $reg->dep_school = $request->dep_school;
            $reg->school = $request->school;
            $reg->organization = $request->organization;
            $reg->achievement = $request->achievement;
            $reg->phone_teacher = $request->phone_teacher;
            // Family
            $reg->phone_parent = $request->phone_parent;
            $reg->father_name = $request->father_name;
            $reg->mother_name = $request->mother_name;
            // Kuesioner
            $reg->ust_idol = $request->ust_idol;
            $reg->smoke = $request->smoke;
            $reg->religion = $request->religion;
            $reg->pondok_know = $request->pondok_know;
            $reg->it_skill = $request->it_skill;
            $reg->like_lesson = $request->like_lesson;
            $reg->pay = $request->pay;
            $reg->start = date('Y-m-d', strtotime($request->start));
            $reg->finish = date('Y-m-d', strtotime($request->finish));

            $reg->cancel = false;
            $reg->status = 1;
            
            
        // Photo
            if ($request->hasFile('photo')) {
                    $photo = $request->file('photo');
                    $photoName = rand(1,99) . $photo->getClientOriginalName();
                    $photo->storeAs('photos', $photoName);
                    $reg->photo = $photoName;
            }

            $reg->save();

            if ($reg->save()) {
            
            // Send Mail
                event(new RegisterEvent($reg));
                return redirect()->route('pendaftaran.pondokit')->with('santri',$request->name);
            } else {
                $reg->email = 'ridwanhasanah3@gmail.com';
                $reg->id_santri = $id_santri.' Gagal Gagal Daftar';
                event(new RegisterEvent($reg));
                return url('/')->with('santri',$id_santri);
            }

    }

    
    /**
     * Search Trafic
     */
    public function search(Request $request)
    {
        $reg = Register::where('id_santri', $request->id_santri)->count();
        $reg2 = Register::where('id_santri', $request->id_santri)->first();
        if ($reg == 1) {

            return response()->json($reg2);
        } else {
            return response()->json('error');
        }

    }
}

resources/views/front-page/register/contact.blade.php
<h3><i class="material-icons">
    perm_contact_calendar
    </i> Kontak</h3>
<div class="row bg-light shadow pt-2 border mb-3">
  <div class="col-xl-4">
    <div class="form-group has-feedback">
      <label class="syarat" for="wa">Nomor WhatsApp</label>
      <input required  value="{{ old('wa') }}" type="text" class="form-control" id="wa" name="wa" placeholder="08xxxxxxxxxx" >
      <span  class="errorval errorRegis" id="error_wa"></span>
      @if ($errors->has('wa'))
      <span class="errorRegis">
        {{$errors->first('wa')}}
      </span>
      @endif
    </div>
  </div>
  <div class="col-xl-4">
    <div class="form-group has-feedback">
      <label class="syarat" for="email">Email</label>
      <input required  value="{{ old('email') }}" type="email" id="email" class="form-control" name="email" placeholder="example@mail.com" >
      <span  class="errorval errorRegis" id="error_email"></span>
      @if ($errors->has('email'))
      <span class="errorRegis">
        {{$errors->first('email')}}
      </span>
      @endif
    </div>
  </div>
  <div class="col-xl-4">
    <div class="form-group has-feedback">
      <label class="syarat" for="facebook">Link Akun Facebook</label>
      <input required  value="{{ old('fb') }}" type="url" class="form-control" id="fb" name="fb" placeholder="https://www.facebook.com/contoh" ></input>
      <span style="color:green;" ><small>Isi dengan link profile facebook kamu</small></span>
      <span  class="errorval errorRegis" id="error_fb"></span>
      @if ($errors->has('fb'))
      <span class="errorRegis">
        {{$errors->first('fb')}}
      </span>
      @endif
    </div> 
  </div>
</div>

resources/views/front-page/register/education.blade.php
<h3> <i class="material-icons">
    school
    </i> Pendidikan</h3>
<div class="row bg-light shadow pt-2 border mb-3">
  <div class="col-xl-4">
    <div class="form-group has-feedback">
      <label class="syarat" for="jurusan">Jurusan  di Sekolah</label>
      <input value="{{ old('dep_school') }}" required value="" type="text" class="form-control" id="dep_school" name="dep_school">
      <span class="errorval errorRegis" id="error_dep_school"></span> @if ($errors->has('dep_school'))
      <span class="errorRegis">
            {{$errors->first('dep_school')}}
          </span> @endif
    </div>
  </div>
  <div class="col-xl-4">
    <div class="form-group has-feedback">
      <label class="syarat" for="sekolah">Asal Sekolah</label>
      <input value="{{ old('school') }}" required value="" type="text" class="form-control" id="school" name="school">
      <span class="errorval errorRegis" id="error_school"></span> @if ($errors->has('school'))
      <span class="errorRegis">
            {{$errors->first('school')}}
          </span> @endif
    </div>
  </div>
  <div class="col-xl-4">
    <div class="form-group has-feedback">
      <label class="syarat" for="sekolah">Nomor Wali Murid / Guru</label>
      <input value="{{ old('phone_teacher') }}" required value="" type="number" class="form-control" id="phone_teacher" name="phone_teacher">
      <span class="errorval errorRegis" id="error_phone_teacher"></span> 
      @if ($errors->has('phone_teacher'))
          <span class="errorRegis">
                {{$errors->first('phone_teacher')}}
          </span> 
      @endif
    </div>
  </div>
  <div class="col-xl-6">
    <div class="form-group has-feedback">
      <label class="syarat" for="organization">Pengalaman Organisai (Optional)</label>
      <textarea type="text" class="form-control" id="organization" name="organization">{{ old('organization') }}</textarea>
      <span class="errorval errorRegis" id="error_organization"></span> 
      @if ($errors->has('organization'))
      <span class="errorRegis">
              {{$errors->first('organization')}}
      </span> 
      @endif
    </div>
  </div>
  <div class="col-xl-6">
    <div class="form-group has-feedback">
      <label class="syarat" for="achievement">Prestasi (Optional)</label>
      <textarea type="text" class="form-control" id="achievement" name="achievement">{{ old('achievement') }}</textarea>
      <span class="errorval errorRegis" id="error_achievement"></span> 
      @if ($errors->has('achievement'))
      <span class="errorRegis">
                {{$errors->first('achievement')}}
      </span> 
      @endif
    </div>
  </div>
</div>

resources/views/front-page/register/family.blade.php
<h3><i class="material-icons">
    group
    </i> Keluarga</h3>
    <div class="row bg-light shadow pt-2 border mb-4">
      <div class="col-xl-4">
        <div class="form-group has-feedback">
          <label class="syarat" for="phone_parent">Nomor Seluler Orang Tua</label>
          <input value="{{ old('phone_parent') }}" required  value="" type="text" class="form-control" id="phone_parent" name="phone_parent" >
           <span  class="errorval errorRegis" id="error_phone_parent"></span>
           @if ($errors->has('phone_parent'))
            <span class="errorRegis">
              {{$errors->first('phone_parent')}}
            </span>
            @endif
        </div>
      </div>
      <div class="col-xl-4">
        <div class="form-group has-feedback">
          <label class="syarat" for="father_name">Nama Ayah</label>
          <input value="{{ old('father_name') }}" required  value="" type="text" id="father_name" class="form-control" name="father_name" >
          <span  class="errorval errorRegis" id="error_father_name"></span>
          @if ($errors->has('father_name'))
          <span class="errorRegis">
            {{$errors->first('father_name')}}
          </span>
          @endif
        </div>
      </div>
      <div class="col-xl-4">
        <div class="form-group has-feedback">
          <label class="syarat" for="mother_name">Nama Ibu</label>
          <input value="{{ old('mother_name') }}" required  value="" type="text" class="form-control" id="mother_name" name="mother_name" >
          <span  class="errorval errorRegis" id="error_mother_name"></span>
          @if ($errors->has('mother_name'))
          <span class="errorRegis">
            {{$errors->first('mother_name')}}
          </span>
          @endif
        </div>
      </div>
    </div>

resources/views/front-page/register/personal-data.blade.php
<h3><i class="material-icons">
    person
    </i> Data Diri</h3>
    <div class="row pt-2 mb-3" id="data-personal">
      <div class="col-xl-4 text-center">
        <h4 style="color: #2A5184;" class="bg-light py-1">Foto Anda</h4>
        <img style="max-width:78%;" class="shadow img-fluid img-thumbnail" src="{{asset('images/user.png')}}" id='img-upload'/>
        <div class="input-group upload">
          <label class="btn btn-outline-primary shadow" for="photo">Upload Foto</label>
          <input value="{{ old('photo') }}" required accept="image/jpeg,image/jpg,image/png," type="file" name="photo" id="photo">
          <span  class="errorval errorRegis" id="error_photo"></span>
        </div>
        @if ($errors->has('photo'))
        <span class="errorRegis">
          {{$errors->first('photo')}}
        </span>
        @endif
        <small class="text-success">
          Hanya file jpg/png/jpeg/gif, Ukuran Gambar maximal 500kb. <br>
        </small>
        </div>
      <div class="col-xl-8">
       <div class="row bg-light shadow pt-2 border mb-3">
          <div class="col-xl-4">
            <div class="form-group valid-form has-feedback">
              <label class="syarat" for="nama">Nama Lengkap</label>
              <input required  value="{{ old('name') }}" type="text" class="form-control" id="name" name="name" placeholder="Masukan nama" >
              <small class="text-success">Isi dengan nama lengkap anda.</small>
               <span  class="errorval errorRegis" id="error_name"></span>
               @if ($errors->has('name'))
                <span class="errorRegis">
                  {{$errors->first('name')}}
                </span>
                @endif
            </div>
          </div>
          <div class="col-xl-4">
            <div class="form-group valid-form has-feedback">
              <label class="syarat" for="divisi">Jenis Kelamin</label>
              <select class="form-control" name="sex" id="sex">
                <option value="">--Pilih--</option>
                <option id="sexp" value="Pria">Pria</option>
                <option id="sexw" value="Wanita">Wanita</option>                       
              </select>
              <span class="errorval errorRegis" id="error_sex"></span>
            </div>
          </div>
          <div class="col-xl-4">
            <div class="form-group has-feedback">
              <label class="syarat" for="tanggal_lahir">Tanggal Lahir</label>
              <input style="cursor: pointer; background:white;"  required value="{{ old('birth_date') }}" id="datepicker" type="text" readonly  class="form-control tanggal_lahir" name="birth_date" placeholder="hari/bulan/tahun" >
              <span  class="errorval errorRegis" id="error_birth_date"></span>
              @if ($errors->has('birth_date'))
              <span class="errorRegis">
                {{$errors->first('birth_date')}}
              </span>
              @endif
            </div>
          </div>
          <div class="col-xl-6">
            <div class="form-group has-feedback">
              <label class="syarat" for="province">Provinsi</label>
              <select class="form-control" name="province" id="province">
                <option value="Jakarta">Jakarta</option>
                <option value="Aceh">Aceh</option>
                <option value="Bali">Bali</option>
                <option value="Banten">Banten</option>
                <option value="Bengkulu">Bengkulu</option>
                <option value="Gorontalo">Gorontalo</option>
                <option value="Jambi">Jambi</option>
                <option value="Jawa Barat">Jawa Barat</option>
                <option value="Jawa Tengah">Jawa Tengah</option>
                <option value="Jawa Timur">Jawa Timur</option>
                <option value="Kalimantan Barat">Kalimantan Barat</option>
                <option value="Kalimantan Selatan">Kalimantan Selatan</option>
                <option value="Kalimantan Tengah">Kalimantan Tengah</option>
                <option value="Kalimantan Timur">Kalimantan Timur</option>
                <option value="Kalimantan Utara">Kalimantan Utara</option>
                <option value="Kepulauan Bangka Belitung">Kepulauan Bangka Belitung</option>
                <option value="Kepulauan Riau">Kepulauan Riau</option>
                <option value="Lampung">Lampung</option>
                <option value="Maluku">Maluku</option>
                <option value="Maluku Utara">Maluku Utara</option>
                <option value="Nusa Tenggara Barat">Nusa Tenggara Barat</option>
                <option value="Nusa Tenggara Timur">Nusa Tenggara Timur</option>
                <option value="Papua">Papua</option>
                <option value="Papua Barat">Papua Barat</option>
                <option value="Riau">Riau</option>
                <option value="Sulawesi Barat">Sulawesi Barat</option>
                <option value="Sulawesi Selatan">Sulawesi Selatan</option>
                <option value="Sulawesi Tengah">Sulawesi Tengah</option>
                <option value="Sulawesi Tenggara">Sulawesi Tenggara</option>
                <option value="Sulawesi Utara">Sulawesi Utara</option>
                <option value="Sumatera Barat">Sumatera Barat</option>
                <option value="Sumatera Selatan">Sumatera Selatan</option>
                <option value="Sumatera Utara">Sumatera Utara</option>
                <option value="Yogyakarta">Yogyakarta</option>
              </select>
              <span  class="errorval errorRegis" id="error_province"></span>
            </div>
          </div>
          <div class="col-xl-6" id="department2">
            <div class="form-group valid-form has-feedback">
              <label class="syarat" for="department">Jurusan Yang Dituju</label>
              <select class="form-control" name="department" id="department">
                <option id="dprogrammer" value="Programmer">Pondok Programmer</option>
                <option id="dmultimedia" value="Multimedia">Pondok Multimedia</option>
                <option id="dimers"  value="Imers">Pondok Imers</option>
                <option id="dcyber" value="Networkers">Pondok Networkers</option>                
              </select>
              <span class="errorval errorRegis" id="error_department"></span>
            </div>
          </div>
          <div class="col-xl-12">
            <div class="form-group has-feedback">
              <label class="syarat" for="addreess">Alamat Rumah</label>
              <textarea required type="text" id="address" class="form-control" name="address" placeholder=" Ex : Jl, Wijoyo Mulyo No.64 Rt/Rw 02/06 Banguntapan..." >{{ old('address') }}</textarea>
              <span  class="errorval errorRegis" id="error_address"></span>
              @if ($errors->has('address'))
              <span class="errorRegis">
                {{$errors->first('address')}}
              </span>
              @endif
            </div>
          </div>
        </div>
      </div>
    </div>

resources/views/front-page/register/questionnaire.blade.php
<h3><i class="material-icons">
    list_alt
    </i> Kuesioner</h3>
<div class="row bg-light shadow pt-2 border mb-3">
  <div class="col-xl-4">
    <div class="form-group has-feedback">
      <label class="syarat" for="ustad">3 Ustad Favorite </label>
      <input type="text" name="ust_idol" id="ust_idol" class="form-control">

      <span class="errorval errorRegis" id="error_ust_idol"></span>
    </div>
  </div>
  <div class="col-xl-4">
    <div class="form-group has-feedback">
      <label class="syarat" for="rokok">Masih Merokok ? </label>
      <select name="smoke" id="smoke" class="form-control">
            <option value="Bukan Perokok">Bukan Perokok</option>
            <option value="Iya">Iya</option>
            <option value="Berusaha Berhenti">Berusaha Berhenti</option>
            <option value="Kadang - Kadang">Kadang - Kadang</option>
            <option value="Sudah Berhenti Total">Sudah Berhenti Total</option>
            <option value="Bukan Perokok Aktiv">Bukan Perokok Aktif</option>
          </select>
      <span class="errorval errorRegis" id="error_smoke"></span>
    </div>
  </div>
  <div class="col-xl-4">
    <div class="form-group has-feedback">
      <label class="syarat" for="pemahaman">Pemahaman Agama</label>
      <input value="{{ old('religion') }}" type="text" id="religion" name="religion" required class="form-control" placeholder="Contoh: Muhammadiyah, NU dll…">
      <span class="errorval errorRegis" id="error_religion"></span> @if ($errors->has('religion'))
      <span class="errorRegis">
            {{$errors->first('religion')}}
          </span> @endif
    </div>
  </div>
  <div class="col-xl-4">
    <div class="form-group has-feedback">
      <label class="syarat">Mulai PKL / Magang</label>
      <input  style="cursor: pointer; background:white;"  id="datepicker-start" type="text" readonly type="text" name="start" class="form-control">
      @if ($errors->has('start'))
            <span class="errorRegis">
              {{$errors->first('start')}}
            </span> 
      @endif

      <span class="errorval errorRegis" id="error_start"></span>
    </div>
  </div>
  <div class="col-xl-4">
    <div class="form-group has-feedback">
      <label class="syarat" for="ustad">Selesai PKL / Magang</label>
      <input  style="cursor: pointer; background:white;"  id="datepicker-finish" type="text" readonly type="text" name="finish" class="form-control">
      @if ($errors->has('finish'))
            <span class="errorRegis">
              {{$errors->first('finish')}}
            </span> 
      @endif

      <span class="errorval errorRegis" id="error_finish"></span>
    </div>
  </div>
  <div class="col-xl-4">
    <div class="form-group has-feedback">
      <label class="syarat" for="Anda_tau"> Dari Mana Anda Mengetahui Pondok IT ? <br></label>
      <select class="form-control" name="pondok_know" id="pondok_know">
              {{-- <option value="">--Pilih--</option> --}}
              <option value="Orang Tua">Orang Tua</option>
              <option value="Guru / Ustadz">Guru / Ustadz</option>
              <option value="Saudara">Saudara</option>
              <option value="Teman">Teman</option>
              <option value="Facebook">Facebook</option>
              <option value="Youtube">Youtube</option>
              <option value="Instagram">Instagram</option>
              <option value="Yang Lain">Yang Lain</option>
          </select>
      <span class="errorval errorRegis" id="error_pondok_know"></span>
    </div>
  </div>
  <div class="col-xl-4">
    <div class="form-group has-feedback">
      <label class="syarat" for="ustad">Siap Alokasi Dana</label>
      <p>
        Alokasi Dana akan di gunakan untuk
        <br>
        Makan-Tempat Tinggal-Listrik-Internet
      </p>
      <select class="form-control" name="pay" id="pay">
        <option value="500rb">500rb</option>
        <option value="600rb">600rb</option>
        <option value="700rb">700rb</option>
        <option value="800rb">800rb</option>
        <option value="900rb">900rb</option>
        <option value="1jt">1jt</option>

      </select>

      <span class="errorval errorRegis" id="error_ust_idol"></span>
    </div>
  </div>
  <div class="col-xl-4">
    <div class="form-group has-feedback">
      <label class="syarat" for="skill">Jelaskan Tentang Skill IT Yang Sudah Dimiliki !</label>
      <textarea style="height: 100px;" name="it_skill" id="it_skill" class="form-control" row bg-lights="8" cols="70">{{ old('it_skill') }}</textarea>
      <span class="errorval errorRegis" id="error_it_skill"></span> 
      @if ($errors->has('it_skill'))
            <span class="errorRegis">
              {{$errors->first('it_skill')}}
            </span> 
      @endif
    </div>
  </div>
  <div class="col-xl-4">
    <div class="form-group has-feedback">
      <label class="syarat" for="bahagia">Pelajaran yang Anda suka ?</label>
      <textarea class="form-control" style="height: 100px;" name="like_lesson" id="like_lesson" row bg-lights="8" cols="70">{{ old('like_lesson') }}</textarea>
      <span class="errorval errorRegis" id="error_like_lesson"></span> @if ($errors->has('like_lesson'))
      <span class="errorRegis">
                          {{$errors->first('like_lesson')}}
                        </span> @endif
    </div>
  </div>
</div>

resources/views/front-page/register/register.blade.php
@extends('front-page.home')
@section('content')
<div id="register-form">
    @include('layouts.patrials.alerts')
  <div class="form container pt-5 mt-5">
    <div class="alert alert-danger" style="display:none"></div>
    <h1 class="text-center text-danger">Form Pendaftaran</h1>
    <form id="formData" method="POST" action="{{route('psb.store')}}" enctype="multipart/form-data">
      {{-- method="POST" action="{{route('psb.store')}}" --}} 
      {{csrf_field()}} {{ method_field('POST') }}
      <div class="load col-xl-6 offset-xl-2" id="loadingDiv"><img src="{{asset('images/loading.gif')}}" alt="loading pendaftaran"></div>
          <div>@include('front-page.register.personal-data')</div>
          <div id="inc-contact">@include('front-page.register.contact')</div>
          <div id="inc-education">@include('front-page.register.education')</div>
          <div id="inc-family">@include('front-page.register.family')</div>
          <div id="inc-questionnaire">@include('front-page.register.questionnaire')</div>
          {{-- <div id="inc-document">@include('front-page.register.document')</div> --}}

          <div class="text-center row  py-4 mb-3">
            <div class="col-xl-12 terms2 p-3">
              <p> 
                <b> 
                  WAJIB !!! <br> <a class="btn btn-primary" target="_blank"style="cursor:pointer" href="https://api.whatsapp.com/send?phone=6285228802828&amp;text=Assalamu%20Alaikum.%20Saya%20Sudah%20Daftar%20di%20Web%20Pendaftaran%20Magang%20PondokIT">JIKA SUDAH MENDAFTAR KONFIRMASI WHATSAPP  0852-2880-2828</a><br>
                  {{-- Jika kirim data gagal silahkan dafta alternatif ke <a class="text-danger" href="https://goo.gl/forms/yS612uUUcRRMyza23" target="_blank">link berikut ini</a>  --}}
                </b>
              </p>
            </div>
            <div class="pt-3" id="inc-send">@include('front-page.register.send')</div>
          </div>
    </form>
  </div>
</div>
@endsection

resources/views/front-page/register/send.blade.php
<div class="form-group kirim">
    <button style="font-weight: bold;" name="submit" value="submit" id="submit" type="submit" class="shadow btn btn-outline-danger btn-lg px-5">Kirim Data</button>
</div>